### ISSUE TITLE
Question about the format of the data

### ISSUE THREAD

**Issue by hsato1** [praveena2j/Joint-Cross-Attention-for-Audio-Visual-Fusion#2]
Hello, Thank you so much for such an interesting research and github repo. 

Could you possibly provide an example of data file format by any chance? I want to try running an inference to a video I have so. 
If I could get some guidance on that, that would be wonderful!

Thank you so much!

Hiro

**Comment by praveena2j** [comment]
I have provided the preprocessing scripts to generate the data file in the required format, Hope it will help you to generate the predictions. 

For your convenience, the label format is image label frameid

**Comment by praveena2j** [comment]
Added the sample label file for your convenience

**Comment by hsato1** [comment]
Thank you for your response!

I see that for audio, I am just feeding in the video with audio, as I look I don't see any cropping and separation done to the visual part and I see that I need to use some other tools such as OpenFace to recovered that information. 

How will I be able to know that these information are temporally aligned?  Because maybe I am not looking into this enough but I don't know how OpenFace actually can help this preprocessing step, and have not been able to find information to help my understanding on that so.

Thank you again,
Hiro

**Comment by praveena2j** [comment]
In this code, we have not used OpenFace, we have used the cropped and aligned face images provided by the dataset organizers
