### ISSUE TITLE
The fusion models

### ISSUE THREAD

**Issue by Romantic1star** [praveena2j/Joint-Cross-Attention-for-Audio-Visual-Fusion#5]
In the README file, it mentions that the fusion models trained using your approach can be found at the following link:  
[Google Drive Link](https://drive.google.com/file/d/1VOlNt5E9UeaBafmpfBjs3LMRzwM2Ggtz/view?usp=sharing).
Unfortunately, I am unable to access the link, as it returns the message: “Sorry, the file you have requested does not exist. Make sure that you have the correct URL and the file exists.”
Could you please check the link and provide an updated version if possible? I appreciate your assistance with this issue.

**Comment by praveena2j** [comment]
I have updated the google drive links

**Comment by Romantic1star** [comment]
After I opened the link, it prompted me to obtain permission. My email address is romantic1star@gmail.com. I hope you can give me permission. Thanks.

**Comment by praveena2j** [comment]
I think I have already provided access
